services:
  - type: web
    name: careerhub-whatsapp-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    disk:
      name: auth
      mountPath: /opt/render/project/src/auth_baileys
      sizeGB: 1
